name: new_alarm_clock
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  sqflite: ^2.0.0+4
  path: ^1.8.0
  vibration: ^1.7.4-nullsafety.0
  syncfusion_flutter_datepicker: ^19.3.48
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.12
  bringtoforeground:
    git:
      url: https://github.com/GiddyNaya/bring_to_foreground.git
      ref: master
  android_alarm_manager_plus: ^1.3.3
  flutter_local_notifications: ^9.2.0
  just_audio: ^0.9.20
  perfect_volume_control: ^1.0.4
  file_picker: ^4.2.6
  jiffy: ^5.0.0
  wakelock: ^0.6.1+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/audio/old_telephone.mp3
    - assets/audio/alarm_clock.mp3

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Jua
      fonts:
        - asset: fonts/Jua-Regular.ttf
          weight: 400
    - family: Noto_Sans_KR
      fonts:
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
          weight: 100
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Light.otf
          weight: 300
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 400
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Black.otf
          weight: 900
    - family: Nanum_Gothic
      fonts:
        - asset: fonts/Nanum_Gothic/NanumGothic-Regular.ttf
          weight: 400
        - asset: fonts/Nanum_Gothic/NanumGothic-Bold.ttf
          weight: 700
        - asset: fonts/Nanum_Gothic/NanumGothic-ExtraBold.ttf
          weight: 800
    - family: TmoneyRoundWind
      fonts:
        - asset: fonts/TmoneyRoundWind/TmoneyRoundWindRegular.ttf
          weight: 400
        - asset: fonts/TmoneyRoundWind/TmoneyRoundWindExtraBold.ttf
          weight: 700

    #Thin            100
    #Extra Light     200
    #Light           300
    #Regular         400
    #Medium          500
    #Semi-Bold       600
    #Bold            700
    #Extra-Bold      800
    #Black           900
